name: Path test

on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'

# There has five jobs in this workflow
# 1. update-to-date
# 2. setup-go
# 3. install-dependencies
# 4. check-version
# 5. passed
jobs:
  update-to-date:
    name: Update to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  setup-go:
    name: Setup go
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
  install-dependencies:
    name: Install dependencies
    needs:
      - setup-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    needs:
      - setup-go
      - install-dependencies
    steps:
      - name: Check version
        run: |
          go version
          ginkgo version
  passed:
    name: Passed
    runs-on: ubuntu-latest
    needs: [update-to-date, setup-go, install-dependencies, check-version]
    if: always()
    steps:
      - name: Passed
        run: |
          echo "Passed"